# Generated by Django 3.2.18 on 2023-03-19 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sump', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('asin', models.CharField(max_length=128, unique=True, verbose_name='书籍名称')),
                ('title', models.CharField(max_length=128, verbose_name='书籍名称')),
                ('description', models.CharField(max_length=128, verbose_name='专辑名称')),
                ('author', models.CharField(max_length=128, verbose_name='作者')),
                ('brand', models.CharField(max_length=128, verbose_name='品牌')),
                ('years', models.CharField(max_length=128, verbose_name='年份')),
                ('num', models.IntegerField(default=0, verbose_name='浏览量')),
                ('imageURL', models.URLField(max_length=256, verbose_name='封面图片')),
            ],
            options={
                'verbose_name': '歌曲',
                'verbose_name_plural': '歌曲',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='标签')),
            ],
            options={
                'verbose_name': '书籍标签',
                'verbose_name_plural': '书籍标签',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('phone', models.CharField(max_length=128, verbose_name='手机号码')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='名字')),
                ('address', models.CharField(max_length=128, verbose_name='地址')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField(verbose_name='评分')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('music', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.book', verbose_name='书籍id')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '评分信息',
                'verbose_name_plural': '评分信息',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=64, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('good', models.IntegerField(default=0, verbose_name='点赞')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.book', verbose_name='书籍')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='collect',
            field=models.ManyToManyField(blank=True, to='user.User', verbose_name='收藏者'),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, to='user.Category', verbose_name='标签'),
        ),
    ]
