# Generated by Django 3.2.18 on 2023-03-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '书籍列表', 'verbose_name_plural': '书籍列表'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户列表', 'verbose_name_plural': '用户列表'},
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=128, verbose_name='书籍描述'),
        ),
    ]
