# Generated by Django 3.2.18 on 2023-03-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230319_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='music',
            new_name='book',
        ),
        migrations.AlterField(
            model_name='book',
            name='asin',
            field=models.CharField(max_length=128, unique=True, verbose_name='书籍编号'),
        ),
    ]
